### ISSUE TITLE
作成画面を決める

### ISSUE THREAD

**Issue by kenkensan** [morijyobi/python_flask_web_final_exercise_2023-kenkensan#1]
## 作成画面一覧

- 管理者ログイン画面
- 予約空き状況確認画面
- 予約状況確認画面
- 管理者アカウント発行画面
- 確認画面
- 管理者情報確認画面
- 利用者情報確認画面
- 利用者情報の登録画面
- 利用者情報の編集、削除画面
- 利用者情報の検索結果画面
- ネット予約情報登録、予約完了メール送信承認画面
- 予約登録画面
- 予約情報の編集、削除画面
- 予約情報閲覧、待ち時間確認画面
- 利用者予約画面
- 利用者予約情報入力フォーム画面
- 利用者待ち時間表示画面

**Comment by kenkensan** [comment]
- ここから変更される可能性もある

**Comment by hosokawa3217** [comment]
作成する画面が決まったら、[README.md](https://github.com/morijyobi/python_flask_web_final_exercise_2023-kenkensan/blob/main/README.md)を更新してください。
